apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-pv-claim
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem